asvspoof_2019_data_path: ...
asvspoof_2021_data_path: ...
path_to_problematic_idxs: ...
path_to_pretrained_wav2vec: ...
path_to_pretrained_aasist: ...
test_data_path: ...

run_name: GOAL

random_state: 43
batch_size: 16
epoch_stop: 16
epochs: 30

aug_prob: 0.
scale: 15
margin: 0.3